name: clean_demo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #BLOC
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3

  # #Firebase
  # firebase_core: ^1.17.0
  # cloud_firestore: ^3.1.15

  #Generate
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

  #Util
  equatable: ^2.0.3
  dartz: ^0.10.1
  intl: ^0.17.0
  flutter_svg: ^1.0.3

dev_dependencies:
  # Testing
  mockito: ^5.2.0
  flutter_test:
    sdk: flutter
  #Lints
  flutter_lints: ^2.0.0
  # Intl
  flutter_intl: ^0.0.1
  intl_utils: ^2.6.1

  #Freezed
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: Language
  main_locale: en
  arb_dir: resources/languages
  output_dir: lib/utils/languages